[package]
name = "nabu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "2.1.1", features = ["json"] }
regex = "1.5.4"               # An implementation of regular expressions for Rust. This implementation uses finite automata and g…
