version: "3.7"
services:
  kilowog-react:
    image: node:lts-slim
    container_name: React
    command: sh -c "cd www && yarn && yarn start"
    depends_on:
      kwe:
        condition: service_started
    ports:
      - 6969:3000
    networks:
      - fNet
      - bNet
    working_dir: /www
    volumes:
      - ./:/www
  kwe:
    image: rustlang/rust:nightly-slim
    command: sh -c "cd kwe && CARGO_HOME=./Cargo.deps cargo run"
    container_name: kwe
    networks:
      - bNet
    #expose: 
    #- 8000
    ports:
      - 8000:8000
    working_dir: /kwe
    volumes:
      - ./:/kwe

networks:
  fNet:
  bNet:
